language: python
python:
  - "3.7"
  - "3.8"
  # - "3.9-dev"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -c conda-forge -n test-environment python=$TRAVIS_PYTHON_VERSION geckodriver
  - conda activate test-environment

  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install -r requirements_snippets.txt
  - pip install -e .
script:
  - make typing
  - pytest -s -v --cov-report=xml --cov=pyteen tests pyteen/snippets
  - codecov
  - make snippet_coverage
